export const SET_ADMIN_LOGIN_SUCCESS = 'SET_ADMIN_LOGIN_SUCCESS'
export const SET_ADMIN_LOGIN_ERROR = 'SET_ADMIN_LOGIN_ERROR'
export const SET_ADMIN_LOGIN_SUCCESS_NULL = 'SET_ADMIN_LOGIN_SUCCESS_NULL'
export const SET_ADMIN_LOGIN_ERROR_NULL = 'SET_ADMIN_LOGIN_ERROR_NULL'
export const SET_LOADING='SET_LOADING'
export const SET_ADMIN_USERNAME_ERROR = 'SET_ADMIN_USERNAME_ERROR'
export const SET_ADMIN_PASSWORD_ERROR = 'SET_ADMIN_PASSWORD_ERROR'
export const SET_ADMIN_LOGIN = 'SET_ADMIN_LOGIN'
export const SET_ADMIN_LOGIN_NULL = 'SET_ADMIN_LOGIN_NULL'
export const SET_ADD_EXAM_SUCCESS = 'SET_ADD_EXAM_SUCCESS'
export const SET_ADD_EXAM_ERROR = 'SET_ADD_EXAM_ERROR'

export const SET_EXAM_DATA = 'SET_EXAM_DATA'
export const SET_QUES_DATA = 'SET_QUES_DATA'
export const SET_STUDENT_DATA = 'SET_STUDENT_DATA'

export const SET_ADD_QUESTION_ERROR = 'SET_ADD_QUESTION_ERROR'
export const SET_ADD_QUESTION_ERROR_NULL = 'SET_ADD_QUESTION_ERROR_NULL'

export const SET_DELETE_QUESTION_SUCCESS = 'SET_DELETE_QUESTION_SUCCESS'
export const SET_DELETE_QUESTION_SUCCESS_NULL = 'SET_DELETE_QUESTION_SUCCESS_NULL'

export const SET_ADD_CLASS_SUCCESS='SET_ADD_CLASS_SUCCESS'
export const SET_ADD_CLASS_NULL='SET_ADD_CLASS_NULL'
export const SET_ADD_CLASS_ERROR='SET_ADD_CLASS_ERROR'
export const SET_ADD_CLASS_ERROR_NULL='SET_ADD_CLASS_ERROR_NULL'

export const SET_CLASS='SET_CLASS'
